/**
 * @file
 * Day 96 – Capstone: Packaging a Real Tool.
 *
 * Scenario: releasing *logslice*, a small command-line tool that cuts a time window out of log
 * files. A release is more than a build: the version is defined once (day.cmake) and reaches the
 * binary through a generated header; the usage text and the Markdown docs are generated from the
 * same option table; the changelog is parsed and checked; and a pre-flight check refuses to ship
 * if any of these disagree.
 *
 * Deliverables (syllabus):
 * - Single-sourced versions
 * - Generated usage docs
 * - A changelog
 * - Pre-flight release checks
 */
#pragma once

#include <fstream>
#include <istream>
#include <optional>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <tuple>
#include <vector>

#include "cppm/lesson.hpp"
#include "logslice_version.hpp"

namespace cppm::day96 {

inline constexpr Deliverable DELIVERABLES[] = {
    {"one option table behind help text and docs", "OPTIONS"},
    {"usage docs generated as Markdown", "markdown_docs"},
    {"parsing a Keep a Changelog file", "parse_changelog"},
    {"checking that a release is a valid semantic-version bump", "valid_bump"},
    {"the pre-flight checklist that gates a release", "preflight"},
};

struct Option {
    const char* flag;
    const char* value;  // "" for switches
    const char* help;
};

/// The single description of the command line. Help text, docs and the parser all read it.
inline constexpr Option OPTIONS[] = {
    {"--from", "HH:MM", "first time to include (default: start of file)"},
    {"--until", "HH:MM", "last time to include, inclusive (default: end of file)"},
    {"--level", "LEVEL", "only lines with this level, e.g. ERROR"},
    {"--count", "", "print the number of matching lines instead of the lines"},
    {"--version", "", "print the version and exit"},
};

inline std::string usage_text() {
    std::string out = std::string("logslice ") + LOGSLICE_VERSION + "\nusage: logslice [options] < app.log\n\noptions:\n";
    for (const auto& o : OPTIONS) {
        std::string left = std::string("  ") + o.flag + (*o.value ? std::string(" ") + o.value : "");
        left.resize(22, ' ');
        out += left + o.help + "\n";
    }
    return out;
}

/// The README section for the tool, generated so it can never drift from the code.
inline std::string markdown_docs() {
    std::string out = std::string("# logslice ") + LOGSLICE_VERSION + "\n\n<!-- generated by markdown_docs(); do not edit -->\n\n"
                      "Cut a time window out of a log read from standard input.\n\n| Option | Value | Description |\n|---|---|---|\n";
    for (const auto& o : OPTIONS) out += std::string("| `") + o.flag + "` | " + (*o.value ? std::string("`") + o.value + "`" : "") + " | " + o.help + " |\n";
    return out;
}

struct Version {
    int major = 0;
    int minor = 0;
    int patch = 0;
    auto operator<=>(const Version&) const = default;
};

inline std::optional<Version> parse_version(const std::string& text) {
    Version v;
    char dot1 = 0;
    char dot2 = 0;
    std::istringstream in(text);
    if (!(in >> v.major >> dot1 >> v.minor >> dot2 >> v.patch) || dot1 != '.' || dot2 != '.' || in.peek() != EOF || v.major < 0 || v.minor < 0 || v.patch < 0) {
        return std::nullopt;
    }
    return v;
}

struct Release {
    std::string version;  // "Unreleased" or "1.3.0"
    std::string date;
    std::vector<std::string> entries;
};

/// "## [1.3.0] - 2026-06-16" headings with "- …" entries below them (### subsections are kept as context).
inline std::vector<Release> parse_changelog(std::istream& in) {
    std::vector<Release> releases;
    for (std::string line; std::getline(in, line);) {
        if (line.rfind("## [", 0) == 0) {
            const auto close = line.find(']');
            if (close == std::string::npos) throw std::runtime_error("bad heading: " + line);
            Release r{line.substr(4, close - 4), "", {}};
            const auto dash = line.find(" - ", close);
            if (dash != std::string::npos) r.date = line.substr(dash + 3);
            releases.push_back(r);
        } else if (line.rfind("- ", 0) == 0 && !releases.empty()) {
            releases.back().entries.push_back(line.substr(2));
        }
    }
    return releases;
}

/// A release must bump exactly one part and reset the parts after it: 1.2.1 -> 1.3.0, 1.2.2 or 2.0.0.
inline bool valid_bump(const Version& from, const Version& to) {
    return to == Version{from.major + 1, 0, 0} || to == Version{from.major, from.minor + 1, 0} ||
           to == Version{from.major, from.minor, from.patch + 1};
}

/// Every problem that should stop a release; empty means "ship it".
inline std::vector<std::string> preflight(const std::string& version, const std::vector<Release>& changelog, const std::string& committed_docs) {
    std::vector<std::string> problems;
    const auto current = parse_version(version);
    if (!current) problems.push_back("version '" + version + "' is not MAJOR.MINOR.PATCH");
    std::vector<const Release*> released;
    for (const auto& r : changelog) {
        if (r.version == "Unreleased") {
            if (!r.entries.empty()) problems.push_back("changelog has unreleased entries – move them under " + version);
        } else {
            released.push_back(&r);
        }
    }
    if (released.empty()) {
        problems.push_back("changelog has no releases");
    } else {
        if (released[0]->version != version) problems.push_back("newest changelog entry is " + released[0]->version + ", binary is " + version);
        if (released[0]->entries.empty()) problems.push_back("release " + released[0]->version + " lists no changes");
        if (released[0]->date.size() != 10) problems.push_back("release " + released[0]->version + " has no YYYY-MM-DD date");
        for (std::size_t i = 0; i + 1 < released.size(); ++i) {
            const auto newer = parse_version(released[i]->version);
            const auto older = parse_version(released[i + 1]->version);
            if (!newer || !older) {
                problems.push_back("unparsable version in changelog near " + released[i]->version);
            } else if (!(*older < *newer)) {
                problems.push_back("changelog is not newest-first at " + released[i]->version);
            } else if (i == 0 && !valid_bump(*older, *newer)) {
                problems.push_back(released[i + 1]->version + " -> " + released[i]->version + " is not a single semantic-version step");
            }
            if (!released[i]->date.empty() && released[i]->date < released[i + 1]->date) problems.push_back("dates go backwards at " + released[i]->version);
        }
    }
    if (committed_docs != markdown_docs()) problems.push_back("USAGE.md is out of date – regenerate it");
    return problems;
}

/// The tool itself: lines start with "HH:MM:SS LEVEL message".
inline int logslice(const std::vector<std::string>& args, std::istream& in, std::ostream& out, std::ostream& err) {
    std::string from = "00:00";
    std::string until = "99:99";
    std::string level;
    bool count = false;
    for (std::size_t i = 0; i < args.size(); ++i) {
        const auto value = [&]() -> std::string {
            if (i + 1 >= args.size()) throw std::invalid_argument(args[i] + " needs a value");
            return args[++i];
        };
        try {
            if (args[i] == "--from") from = value();
            else if (args[i] == "--until") until = value();
            else if (args[i] == "--level") level = value();
            else if (args[i] == "--count") count = true;
            else if (args[i] == "--version") return (out << "logslice " << LOGSLICE_VERSION << '\n'), 0;
            else throw std::invalid_argument("unknown option " + args[i]);
        } catch (const std::invalid_argument& e) {
            err << "logslice: " << e.what() << '\n' << usage_text();
            return 2;
        }
    }
    int matched = 0;
    std::string last_time = "00:00";
    for (std::string line; std::getline(in, line);) {
        const bool stamped = line.size() >= 8 && line[2] == ':' && line[5] == ':';
        if (stamped) last_time = line.substr(0, 5);  // continuation lines inherit the previous time
        if (last_time < from || last_time > until) continue;
        if (!level.empty() && (!stamped || line.find(" " + level + " ") != 8)) continue;
        ++matched;
        if (!count) out << line << '\n';
    }
    if (count) out << matched << '\n';
    return 0;
}

inline std::string read_file(const std::string& path) {
    std::ifstream in(path, std::ios::binary);
    if (!in) throw std::runtime_error("cannot read " + path);
    std::ostringstream text;
    text << in.rdbuf();
    return text.str();
}

/// The interactive demo: "check" runs the pre-flight on the real files; "slice <args>" runs the tool on a sample log.
inline int run(std::istream& in, std::ostream& out) {
    out << "Day 96 – Capstone: Packaging a Real Tool\n" << usage_text();
    const std::string sample = "09:58:01 INFO start\n10:00:05 ERROR disk full\n  at write()\n10:02:00 INFO retry ok\n10:07:30 ERROR timeout\n";
    while (auto line = prompt_line(in, out, "check | docs | slice <options>> ")) {
        std::istringstream words(*line);
        std::string command;
        if (!(words >> command)) break;
        if (command == "check") {
            std::ifstream changelog(std::string(LOGSLICE_SOURCE_DIR) + "/release/CHANGELOG.md");
            const auto problems = preflight(LOGSLICE_VERSION, parse_changelog(changelog), read_file(std::string(LOGSLICE_SOURCE_DIR) + "/release/USAGE.md"));
            out << (problems.empty() ? "  pre-flight passed: ready to tag v" + std::string(LOGSLICE_VERSION) + "\n" : "");
            for (const auto& p : problems) out << "  BLOCKER: " << p << '\n';
        } else if (command == "docs") {
            out << markdown_docs();
        } else if (command == "slice") {
            std::vector<std::string> args;
            for (std::string a; words >> a;) args.push_back(a);
            std::istringstream log(sample);
            logslice(args, log, out, out);
        }
    }
    return 0;
}

}  // namespace cppm::day96
